name: bullet_force_hax
# description:
# version: 1.0.0
# homepage: https://www.example.com
# author: Example <email@example.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=1.2.0 <3.0.0'
  pedantic: ^1.7.0
  test: ^1.6.0
  buffer: ^1.0.6
  js: ^0.6.0
