[package]
name = "bulletforcehax"
version = "0.1.0"
authors = ["HoLLy"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.6"
log = "0.4"
console_log = "0.1.2"
byteorder = "1.3"
maplit = "1"
