# taken from https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md,
# which is licensed under CC0

on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path bulletforcehax/libs/photon_core/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path bulletforcehax/libs/photon_derive/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path bulletforcehax/libs/photon/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path bulletforcehax/Cargo.toml

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path bulletforcehax/libs/photon_core/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path bulletforcehax/libs/photon_derive/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path bulletforcehax/libs/photon/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path bulletforcehax/Cargo.toml

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path bulletforcehax/libs/photon_core/Cargo.toml -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path bulletforcehax/libs/photon_derive/Cargo.toml -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path bulletforcehax/libs/photon/Cargo.toml -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path bulletforcehax/Cargo.toml -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path bulletforcehax/libs/photon_core/Cargo.toml -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path bulletforcehax/libs/photon_derive/Cargo.toml -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path bulletforcehax/libs/photon/Cargo.toml -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path bulletforcehax/Cargo.toml -- -D warnings
